# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user', models.CharField(max_length=32)),
                ('date', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=50)),
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('date', models.IntegerField()),
                ('itemName', models.CharField(max_length=32)),
                ('itemLink', models.CharField(max_length=50)),
                ('itemReview', models.CharField(max_length=250)),
                ('itemSize', models.CharField(max_length=32)),
                ('itemPic', models.CharField(max_length=75)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Post')),
            ],
        ),
    ]
