# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='itemLink',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='itemName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='itemPic',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='review',
            name='itemReview',
            field=models.CharField(max_length=1500),
        ),
    ]
